name: PHPStan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


permissions:
  contents: read
  security-events: write

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Download PHPStan
        run: |
          wget https://github.com/phpstan/phpstan/releases/latest/download/phpstan.phar
          chmod +x phpstan.phar
          mkdir -p tools
          mv phpstan.phar tools/phpstan
      
      - name: Run PHPStan via Action
        uses: php-actions/phpstan@v3
        with:
          phpstan_path: tools/phpstan
          path: src/


      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: phpstan.sarif
