name: PHPStan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Set up PHPStan and GitHub extension (no Composer global)
        run: |
          mkdir -p tools/phpstan
          cd tools/phpstan
          
          # Download phpstan.phar
          wget https://github.com/phpstan/phpstan/releases/latest/download/phpstan.phar
          chmod +x phpstan.phar

          # Init composer locally & require the GitHub formatter
          composer init -n
          composer require --dev phpstan/phpstan-github

          cd ../..

      - name: Run PHPStan with GitHub SARIF formatter
        run: |
          ./tools/phpstan/phpstan/phpstan.phar analyse src \
            --error-format=github > phpstan-results.sarif
        env:
          COMPOSER_PROCESS_TIMEOUT: 0

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: phpstan-results.sarif
