name: PHPStan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download PHPStan
        run: |
          wget https://github.com/phpstan/phpstan/releases/latest/download/phpstan.phar
          chmod +x phpstan.phar
          mkdir -p tools
          mv phpstan.phar tools/phpstan

      - name: Run PHPStan manually
        run: |
          ./tools/phpstan analyse src/ --error-format=sarif > phpstan-results.sarif

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: phpstan-results.sarif
