name: Psalm Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  php-security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # or your PHP version
          tools: composer

      - name: Install Psalm and Security Plugin
        run: |
          composer require --dev vimeo/psalm psalm/plugin-security-analysis
          ./vendor/bin/psalm-plugin enable psalm/plugin-security-analysis

      - name: Run Psalm with Taint Analysis
        run: |
          ./vendor/bin/psalm --taint-analysis --no-progress --show-info=false --output-format=sarif > psalm-results.sarif

      - name: Upload Psalm SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: psalm-results.sarif
