name: Psalm Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  php-security:
    name: Psalm – Static Analysis for PHP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Psalm Static Analysis
        uses: psalm/psalm-github-actions@2.3.0
        with:
          security_analysis: true
          show_info: false
          composer_require_dev: true
          report_file: results.sarif
          composer_ignore_platform_reqs: true  # Optional: if you have platform constraints

      - name: Upload SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
