name: Psalm Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  php-security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install Psalm
        run: |
          composer require --dev vimeo/psalm:^5.0

      - name: Run Psalm with Taint Analysis
        run: |
          ./vendor/bin/psalm --taint-analysis --no-progress --show-info=false --output-format=sarif > psalm-results.sarif || true

      - name: Upload Psalm SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: psalm-results.sarif


      - name: Upload Psalm JSON results
        uses: actions/upload-artifact@v4
        with:
          name: psalm-json-report
          path: psalm-results.json
          if-no-files-found: ignore
