name: Psalm Security Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  php-security-scan:
    name: Psalm Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install Psalm
        run: composer require --dev vimeo/psalm:^5.0 --no-progress

      - name: Run Psalm with Taint Analysis
        run: |
          ./vendor/bin/psalm --taint-analysis --no-progress --show-info=false --output-format=sarif --output=psalm-results.sarif
          # Exit code 0 - no errors found
          # Exit code 1 - errors found
          # Exit code 2 - config/other issues
          # We want to proceed with SARIF upload even if errors found (exit code 1)
          if [ $? -eq 2 ]; then exit 1; fi

      - name: Run Psalm Scan (SARIF & JSON)
        run: |
          psalm --config=p/php --sarif --output=psalm-results.sarif
          psalm --config=p/php --json --output=psalm-results.json

      - name: Upload SARIF results (for GitHub Code Scanning)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: psalm-results.sarif

      - name: Upload psalm JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: psalm-json-report
          path: psalm-results.json
          if-no-files-found: ignore
