name: Psalm Security Analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  security-events: write

jobs:
  php-security-scan:
    name: Psalm Security Scan (No Config)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install Psalm
        run: composer require --dev vimeo/psalm:^5.0 --no-progress

      - name: Run Psalm Scan (SARIF + JSON)
        run: |
          ./vendor/bin/psalm --no-config --output-format=sarif > psalm-results.sarif || exit_code=$?
          ./vendor/bin/psalm --no-config --output-format=json > psalm-results.json || true
          if [ "${exit_code:-0}" = "2" ]; then
            echo "Psalm config or fatal error detected"
            exit 1
          fi
          exit ${exit_code:-0}

      - name: Upload SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: psalm-results.sarif

      - name: Upload Psalm JSON report
        uses: actions/upload-artifact@v4
        with:
          name: psalm-json-report
          path: psalm-results.json
          if-no-files-found: ignore
