name: Semgrep Security Scan

on:
  push:
    branches: [ "main", "develop", "next" ]
  pull_request:
    branches: [ "main", "develop", "next" ]

jobs:
  semgrep-scan:
    name: Run Semgrep Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          python -m pip install semgrep
          semgrep --version

       # --- PHP Security Scan (p/php) ---
      - name: Run Semgrep Scan (PHP, SARIF Output)
        run: |
          semgrep --config=p/php --sarif --output=semgrep-php.sarif .
      - name: Run Semgrep Scan (PHP, JSON Output)
        run: |
          semgrep --config=p/php --json --output=semgrep-php.json .
          
      # --- Secrets Scan (p/secrets) ---
      - name: Run Semgrep Scan (Secrets, SARIF Output)
        run: |
          semgrep --config=p/secrets --sarif --output=semgrep-secrets.sarif .
      - name: Run Semgrep Scan (Secrets, JSON Output)
        run: |
          semgrep --config=p/secrets --json --output=semgrep-secrets.json .
          
      # --- Security Audit Scan ---
      - name: Run Semgrep Scan (Security Audit, SARIF Output)
        run: |
          semgrep --config=p/security-audit --sarif --output=semgrep-security-audit.sarif .
      - name: Run Semgrep Scan (Security Audit, JSON Output)
        run: |
          semgrep --config=p/security-audit --json --output=semgrep-security-audit.json .

      # --- OWASP Top 10 Scan ---
      - name: Run Semgrep Scan (OWASP Top Ten, SARIF Output)
        run: |
          semgrep --config="p/owasp-top-ten" --sarif --output=semgrep-owasp-top-ten.sarif .
      
      - name: Run Semgrep Scan (OWASP Top Ten, JSON Output)
        run: |
          semgrep --config="p/owasp-top-ten" --json --output=semgrep-owasp-top-ten.json .


      # --- Upload additional SARIF results ---
      - name: Upload PHP SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-php.sarif
          category: semgrep-php
        if: always()

      - name: Upload Secrets SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-secrets.sarif
          category: semgrep-secrets
        if: always()
      
      - name: Upload Security Audit SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-security-audit.sarif
          category: semgrep-security-audit
        if: always()

      - name: Upload OWASP Top Ten SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-owasp-top-ten.sarif
          category: semgrep-owasp-top-ten
        if: always()
      
      - name: Upload all Semgrep Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-security-reports
          path: |
            semgrep-php.sarif
            semgrep-php.json
            semgrep-secrets.sarif
            semgrep-secrets.json
            semgrep-security-audit.sarif
            semgrep-security-audit.json
            semgrep-owasp-top-ten.sarif
            semgrep-owasp-top-ten.json
        if: always()

