name: Semgrep Security Scan

on:
  push:
    branches: [ "main", "develop", "next" ]
  pull_request:
    branches: [ "main", "develop", "next" ]

jobs:
  semgrep-scan:
    name: Run Semgrep Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install Semgrep
        run: |
          python -m pip install semgrep
          semgrep --version
           # --- Security Audit Scan ---
      - name: Run Semgrep Scan (Security Audit, SARIF Output)
        run: |
          semgrep --config=p/security-audit --sarif --output=semgrep-security-audit.sarif .
      - name: Run Semgrep Scan (Security Audit, JSON Output)
        run: |
          semgrep --config=p/security-audit --json --output=semgrep-security-audit.json .

      # --- OWASP Top 10 Scan ---
      - name: Run Semgrep Scan (OWASP Top 10, SARIF Output)
        run: |
          semgrep --config=p/owasp-top10 --sarif --output=semgrep-owasp-top10.sarif .
      - name: Run Semgrep Scan (OWASP Top 10, JSON Output)
        run: |
          semgrep --config=p/owasp-top10 --json --output=semgrep-owasp-top10.json .

      # --- Upload additional SARIF results ---
      - name: Upload Security Audit SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-security-audit.sarif
          category: semgrep-security-audit
        if: always()

      - name: Upload OWASP Top 10 SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-owasp-top10.sarif
          category: semgrep-owasp-top10
        if: always()

      # --- Upload all reports as artifact ---
      - name: Upload all Semgrep Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-security-reports
          path: |
            semgrep-php.sarif
            semgrep-php.json
            semgrep-secrets.sarif
            semgrep-secrets.json
            semgrep-security-audit.sarif
            semgrep-security-audit.json
            semgrep-owasp-top10.sarif
            semgrep-owasp-top10.json
        if: always()
